# Site settings
title: Marco Garcês
tag_text: Marco Garcês - sysadmin
description: sysadmin by day, superhero by night
url: "https://marco.garces.cc"

# Build settings
markdown: kramdown

exclude: ["README.md"]
